// <auto-generated />
using System;
using DataAccess.EfImplementations.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DersDb2Context))]
    partial class DersDb2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Clients.IdentityCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RegisterAdress");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("IdentityCards", "client");
                });

            modelBuilder.Entity("Entities.Clients.MobileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("PhoneNumbers", "client");
                });

            modelBuilder.Entity("Entities.Clients.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PersonSalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Salary");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("NoToken");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken");

                    b.ToTable("People", "client");
                });

            modelBuilder.Entity("Entities.Clients.SalaryHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("NewSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("SalaryHistory", "client");
                });

            modelBuilder.Entity("Entities.Compositions.PersonLessonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("LessonId");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonLessonCompositions", "composition");
                });

            modelBuilder.Entity("Entities.Compositions.PersonMobileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonPhoneNumberCompositions", "composition");
                });

            modelBuilder.Entity("Entities.Educations.LessonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lessons", "education");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyName = "MexMat",
                            SpecialtyName = "Riyaziyyat"
                        },
                        new
                        {
                            Id = 2,
                            FacultyName = "MexMat",
                            SpecialtyName = "Mexanika"
                        },
                        new
                        {
                            Id = 3,
                            FacultyName = "Kibernetika",
                            SpecialtyName = "Komputer muhendisli"
                        },
                        new
                        {
                            Id = 4,
                            FacultyName = "Kibernetika",
                            SpecialtyName = "Informatika"
                        },
                        new
                        {
                            Id = 5,
                            FacultyName = "Dil ve Edebiyyat",
                            SpecialtyName = "Serq Etomologiyasi"
                        },
                        new
                        {
                            Id = 6,
                            FacultyName = "Tarix",
                            SpecialtyName = "Azerbaycan Tarixi"
                        },
                        new
                        {
                            Id = 7,
                            FacultyName = "Tarix",
                            SpecialtyName = "Rus Tarixi"
                        });
                });

            modelBuilder.Entity("Entities.Educations.StudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Students", "education");
                });

            modelBuilder.Entity("Entities.Clients.IdentityCardEntity", b =>
                {
                    b.HasOne("Entities.Clients.PersonEntity", "Person")
                        .WithOne("IdentityCard")
                        .HasForeignKey("Entities.Clients.IdentityCardEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Clients.SalaryHistoryEntity", b =>
                {
                    b.HasOne("Entities.Clients.PersonEntity", "Person")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Compositions.PersonLessonEntity", b =>
                {
                    b.HasOne("Entities.Educations.LessonEntity", "Lesson")
                        .WithMany("PersonLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Clients.PersonEntity", "Person")
                        .WithMany("PersonLessons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Compositions.PersonMobileEntity", b =>
                {
                    b.HasOne("Entities.Clients.MobileEntity", "Mobile")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Clients.PersonEntity", "Person")
                        .WithMany("PersonMobiles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mobile");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Educations.StudentEntity", b =>
                {
                    b.HasOne("Entities.Clients.PersonEntity", "Person")
                        .WithOne("Student")
                        .HasForeignKey("Entities.Educations.StudentEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Clients.PersonEntity", b =>
                {
                    b.Navigation("IdentityCard");

                    b.Navigation("PersonLessons");

                    b.Navigation("PersonMobiles");

                    b.Navigation("SalaryHistories");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Educations.LessonEntity", b =>
                {
                    b.Navigation("PersonLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
